server:
  port: 8086

api:
  polygon:
    domain: 'api.polygon.io'
    version: 'v2/'
    endpoint: 'aggs/'
    path: 'ticker/'
    ticker:
      cryptoTicker: 'X:BTCUSD'
    params:
     adjusted: 'true'
     apiKey: '0pBc6wIRoFmb0jiNfpQkQtphDb9u_e7K'

