server:
  port: 8086

api:
  polygon:
    domain: 'api.polygon.io'
    simple:
      version: 'v2'
      endpoint: '/aggs/ticker/'
      ticker:
        cryptoTicker: 'X:BTCUSD'
      range:
        multiplier: '/1'
        timespan: '/day'
        from: '/2023-01-09'
        to: '/2023-01-09'
      params:
        adjusted: 'true'
        sort: 'asc'
        limit: '120'
        apiKey: '0pBc6wIRoFmb0jiNfpQkQtphDb9u_e7K'
