server:
  port: 8085

api:
  coingecko:
    domain: 'api.coingecko.com'
    market:
    #https://api.coingecko.com/api/v3/
    #coins/markets
    #?vs_currency=usd&
    # order=market_cap_desc&
    # per_page=100&
    # page=1&
    # sparkline=false&
    # locale=en
      endpoint: '/coins/markets'
      pathSegment: 'api'
      version: 'v3'
      params:
        vs_currency: 'usd'
        order: 'market_cap_desc'
        per_page: '100'
        page: '1'
        sparkline: 'false'
        locale: 'en'
      # https://api.coingecko.com/api/v3/
      # simple/
      # price?ids=Bitcoin%2CEthereum%2CTether%2CDogecoin&
      #vs_currencies=usd%2Chkd
      
      #https://api.coingecko.com/api/v3/simple/price?ids=Bitcoin
      #%2CEthereum%2CTether%2CDogecoin&vs_currencies=usd%2Chkd
    simple:
      endpoint2: '/simple'
      pathSegment: 'api'
      version: 'v3'
      params2: 
        ids: 'Bitcon,Ethereum,Tether,Dogecoin'
        vs_currencies: 'usd,hkd'
      # ?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false
