server:
  port: 8085

coingecko:
  baseUrl: api.coingecko.com
  serviceVers: /api/v3
  service:
      coins-markets:
        serviceUrl: /coins/markets
        currency: usd
        order: market_cap_desc
        perPage: 100
        page: 1
        sparkline: false
      simple-price:
        serviceUrl: simple/price

#==========redis 配置信息===========#
spring.data.redis:
  #（单机redis）数据库ip
  host: 127.0.0.1
  #（单机redis）数据库端口
  port: 6379
  #数据库指定索引
  database: 0
  #数据库密码
  password:
  timeout: 5000
  jedis.pool:
    #连接池最大连接数，负值表示不限制
    max-active: 1000
    #连接池中最大空闲连接
    max-idle: 10
    #连接池中最小空闲连接
    min-idle: 2
    #连接池最大阻塞等待时间，负值表示不限制
    max-wait: -1
