server:
  port: 8085

api:
  coingecko:
    domain: 'api.coingecko.com'
    market:
      # ?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false
      endpoint: '/coins/markets'
      pathSegment: 'api'
      version: 'v3'
      params:
        vs-currency: 'usd'
        order-by: 'market_cap_desc'
        per-page: '100'
        page: '1'
        sparkline: 'false'
    simple-price:
      # ?ids=bitcoin,ethereum,tether,dogecoin,ripple&vs_currencies=usd,hkd
      endpoint: '/simple/price'
      pathSegment: 'api'
      version: 'v3'
      # params:
        # ids: 'bitcoin,ethereum,tether,dogecoin,ripple'
        # vs-currencies: 'usd,hkd'