server:
  port: 8085

api:
  coingecko:
    domain: 'api.coingecko.com'
    market:
      # ?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false
      endpoint: '/coins/markets'
      pathSegment: 'api'
      version: 'v3'
      params:
        vs_currency: 'usd'
        order: 'market_cap_desc'
        per_page: '100'
        page: '1'
        sparkline: 'false'
        locale: 'en'


