server:
  port: 8087

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: 
  password: 
spring.jpa:
  show-sql: true
  properties: # optional to under "properties"
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      # Either to use hibernate or spring.sql.init, otherwise it duplicated to create tables
      ddl-auto: none # create, create-drop, update, none, validate
spring.sql.init:
  schema-locations: 
    - classpath:ddl/DROP_CHANNEL_TRANS.sql
    - classpath:ddl/DROP_CHANNEL_MAPS.sql
    - classpath:ddl/DROP_CHANNEL_COIN_MAPPINGS.sql
    - classpath:ddl/DROP_CHANNELS.sql
    - classpath:ddl/DDL_CHANNELS.sql
    - classpath:ddl/DDL_CHANNEL_MAPS.sql
    - classpath:ddl/DDL_CHANNEL_TRANS.sql
    - classpath:ddl/DDL_CHANNEL_COIN_MAPPINGS.sql
  # data-locations:
  mode: always # always, embeded, never