server:
  port: 8088

api:
  crypto:
    admin:
      domain: localhost:8087/crypto/admin
      endpoints:
        channel:
          version: v1
          endpoint: '/channel/mapping'
        transaction:
          version: v1
          endpoint: '/channel/service'
