server:
  port: 8030

service:
  admin:
    baseUrl: http://localhost:8087 # admin-service host
    serviceVers: crypto/admin/api/v1
    endpoint:
      channel-url: channel/{id}
      coinmap-url: channel/coins # for approach 1
      transaction-url: channel/transactions
      # coinmap-url2: channel/{id}/coinmap2 # for approach 2
  coingecko:
    baseUrl: http://localhost:8085 # coingecko-service host
    serviceVers: crypto/v1/coingecko
    serviceUrl1: coin/market
    serviceUrl2: coins/exchangerates
  polygon:
    baseUrl: http://localhost:8086 # polygon-service host
    serviceVers: crypto/v1/polygon
    serviceUrl: /price
