CREATE TABLE CHANNEL_TRANS(
  ID INTEGER auto_increment primary key,
  CHANNEL_ID INTEGER NOT NULL , --1
  DOMAIN_VERSION VARCHAR(100) NOT NULL, --1 crypto/coingecko/api/v1
  DOMAIN_URL VARCHAR(100) NOT NULL , -- price
  SOURCE_APP VARCHAR(20) NOT NULL, --crypto-web
  TRAN_TYPE VARCHAR(20) NOT NULL , --ex-rate
  LAST_UPD_DATE DATETIME NOT NULL DEFAULT current_timestamp,
  CONSTRAINT UC_TRAN UNIQUE (SOURCE_APP , TRAN_TYPE),
  CONSTRAINT FK_CHANNEL_TRAN FOREIGN KEY (CHANNEL_ID) REFERENCE CHANNEL_CODE
  );