CREATE TABLE CHANNEL_COIN_MAPPINGS (
  id INTEGER  auto_increment primary key,
  CHANNEL_ID INTEGER NOT NULL,
  COIN_CODE VARCHAR(50)NOT NULL,
  COIN_ID VARCHAR(50) NOT NULL,
  LAST_UPD_DATE DATETIME NOT NULL DEFAULT current_timestamp,
  CONSTRAINT UC_COIN_MAPPING UNIQUE ( CHANNEL_ID,COIN_CODE),
  CONSTRAINT FK_CHANNEL_COIN_MAPPING FORIEGN KEY (CHANNEL_ID) REFERENCE CHANNELS(ID)
 );