CREATE TABLE CHANNEL_TRANS (
    ID SERIAL PRIMARY KEY,
    CHANNEL_ID INTEGER NOT NULL, -- 1
    TRAN_TYPE VARCHAR(20) NOT NULL, -- EXCHANGE
    SERVICE_VERSION VARCHAR(100) NOT NULL, -- crypto/v1/coingecko
    SERVICE_ENDPOINT VARCHAR(100) NOT NULL, -- exchange
    LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_CHANNEL_TRAN UNIQUE (CHANNEL_ID, TRAN_TYPE),
    CONSTRAINT FK_CHANNEL_TRAN FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)
);