CREATE TABLE CHANNELS(
  ID INTEGER AUTO_INCREMENT primary key,
  CHANNEL_CODE VARCHAR(50) NOT NULL,
  CHANNEL_URL VARCHAR(50) NOT NULL,
  LAST_UPD_DATE DATETIME NOT NULL DEFAULT current_timestamp,
  CONSTRAINT UC_CHANNEL UNIQUE (CHANNEL_CODE)
);