CREATE TABLE CHANNEL_MAPS (
    ID SERIAL PRIMARY KEY,
    SOURCE VARCHAR(20) NOT NULL, -- WEB, MOBILE
    TRAN_TYPE VARCHAR(20) NOT NULL, -- EXCHANGE
    CHANNEL_ID INTEGER NOT NULL, -- COINGECKO, POLYGON
    LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_CHANNEL_MAP UNIQUE (SOURCE, TRAN_TYPE),
    CONSTRAINT FK_CHANNEL_MAP FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)
);