CREATE TABLE CHANNELS (
    ID SERIAL PRIMARY KEY,
    CHANNEL_CODE VARCHAR(50) NOT NULL, -- COINGECKO, POLYGON
    CHANNEL_DOMAIN VARCHAR(100) NOT NULL, -- api.coingecko.com
    LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_CHANNEL UNIQUE (CHANNEL_CODE)
); 