CREATE TABLE CHANNEL_COIN_MAPPINGS (
    ID SERIAL PRIMARY KEY,
    CHANNEL_ID INTEGER NOT NULL, -- 1
    COIN_CODE VARCHAR(10) NOT NULL, -- BTC/ USDT
    COIN_ID VARCHAR(50) NOT NULL, -- bitcoin
    LAST_UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_CHANNEL_COIN_MAPPING UNIQUE (CHANNEL_ID, COIN_CODE),
    CONSTRAINT FK_CHANNEL_COIN_MAPPING FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)
);